### ISSUE TITLE
How to compile this?

### ISSUE THREAD

**Issue by latenightz** [thebigcx/operating-system#1]
Hi, I was wondering how I would compile this?

**Comment by thebigcx** [comment]
If you're on Linux or Mac, `make` in boot/ will create the EFI file and `make` in kernel/ will build the kernel.
Then `make` in the root directory to create a .iso and `sh qemu.sh` to emulate. GNU-EFI, OVMF, and QEMU are needed, but a simple `pacman -S gnu-efi ovmf qemu` should do the trick.

If you're on Windows, I'm not quite sure, but using the same build process through WSL might work.

**Comment by latenightz** [comment]
I keep getting the error: "/usr/local/lib/crt0-efi-x86_64.o" not found

**Comment by thebigcx** [comment]
I will put a pre-built .iso file in the bin/ directory, you could try running that with qemu.

**Comment by thebigcx** [comment]
Try building GNU-EFI from source from [here](https://sourceforge.net/projects/gnu-efi/), and let me know if that fixes the problem.

**Comment by thebigcx** [comment]
os.iso is available in ```bin/```, you should be able to run this with any emulation software that supports UEFI, though QEMU is known to work properly.

**Comment by latenightz** [comment]
there's no `os.iso` in bin/
